# Generated by Django 4.1 on 2022-08-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
